package helloworldexample;
// Generated Jan 9, 2017 10:28:21 AM by Hibernate Tools 4.3.1


import javax.persistence.*;

/**
 * Message generated by hbm2java
 */
@Entity
@Table
public class Message implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Short id;
    @Column
    private String message;

    public Message() {
    }

    public Message(String message) {
        this.message = message;
    }

    public Short getId() {
        return this.id;
    }

    public void setId(Short id) {
        this.id = id;
    }

    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }


}
